services:
  app:
    image: yuyeonho/receiptpower-server:cagong  # GitHub Packages 이미지
    container_name: receiptpower-service
    ports:
      - "80:8080"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    env_file:
      - .env
    restart: always
