spring:
  datasource:
    url: "jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT:3306}/${DATABASE_NAME}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${CLIENT_SECRET}"
            client-secret: "${CLIENT_SECRET}"
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
            client-name: Google

jwt:
  secret: "${JWT_SECRET}"