spring:
  datasource:
    url: jdbc:mysql://localhost:3306/receipt
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: ThisIsA_VeryLongAndSecureSecretKeyForJwt_YouShouldChangeThis